In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np 
import matplotlib.pyplot as plt
import scipy.sparse as sp
from pypde.solver.matrix import *
from pypde.solver.solverplan import *

A = np.array([[1,1,2],[0,3,6],[0,0,9]])
b = np.array([[0,1,2],[3,4,6],[7,8,9]])
x = np.array([1,2,3])
b = np.vstack((b,x))
b.shape
#A@b
#b@A.T

(4, 3)

In [2]:
M = MatrixBase(A,axis=1,sparse=False)
M.T
M.dot(b)

array([[ 5, 15, 18],
       [19, 48, 54],
       [33, 78, 81],
       [ 9, 24, 27]])

In [3]:
lhs = SolverPlanLHS(A,ndim=2,axis=1,method="numpy")


In [4]:
lhs.A
lhs.solve(b)

b.shape

(4, 3)

## twodma

In [7]:
N = 5
l = np.random.rand(N-2)
d = np.random.rand(N)
u = np.random.rand(N-2)
u1 = np.random.rand(N-4)
A = np.diag(d,0) + np.diag(u,2) + np.diag(u1,4) + np.diag(l,-2)
b = np.random.rand(4,N)

lhs = SolverPlanLHS(A,ndim=2,axis=1,method="fdma")
x = b.copy(order="F")
x = lhs.solve(x)
print(x)

[[  0.05385225  -3.7675829    2.78638673   4.36464208  -1.97119937]
 [  4.81327974  -7.14021712  16.67012427   6.90484528 -17.65999698]
 [  0.51388985   1.08993697   0.23742693  -0.26131564  -0.16470595]
 [  0.03456056   0.32778913  -1.16497837   0.4236684    2.01130963]]


In [8]:

x = np.linalg.solve(A,b.T).T
print(x)

[[  0.05385225  -3.7675829    2.78638673   4.36464208  -1.97119937]
 [  4.81327974  -7.14021712  16.67012427   6.90484528 -17.65999698]
 [  0.51388985   1.08993697   0.23742693  -0.26131564  -0.16470595]
 [  0.03456056   0.32778913  -1.16497837   0.4236684    2.01130963]]
