## Solverplan

In [4]:
%load_ext autoreload
%autoreload 2
from pypde.solver.plans import *
from pypde.solver.solverplan import *
A = np.array([[1,1,2],[0,3,6],[0,0,9]])
b = np.array([[0,1,2],[3,4,6]])

# Make Plans
rhs = PlanRHS(A,ndim=2,axis=1)
lhs = PlanLHS(A,ndim=2,axis=1,method="numpy")

# Add them
solver = SolverPlan()
solver.add_lhs(lhs)
solver.add_rhs(rhs)

# Print them
solver.show_plan()

# Solve them
rhs = solver.solve_rhs(b)
x = solver.solve_lhs(rhs)
print(x)

# The above results should be the same as
rhs = b@A.T
np.linalg.solve(A,rhs.T).T

Plans RHS:
1 ) Apply method 'multiply' along axis 1 

Plans LHS:
1 ) Apply method 'numpy' along axis 1 

[[0. 1. 2.]
 [3. 4. 6.]]


array([[0., 1., 2.],
       [3., 4., 6.]])