In [14]:
%load_ext autoreload
%autoreload 2
import numpy as np 
import matplotlib.pyplot as plt
import scipy.sparse as sp
from pypde.solver.matrix import *
from pypde.solver.plans import *
from pypde.solver.solverplan import *

A = np.array([[1,1,2],[0,3,6],[0,0,9]])
b = np.array([[0,1,2],[3,4,6],[7,8,9]])
x = np.array([1,2,3])
b = np.vstack((b,x))
b.shape
#A@b
#b@A.T

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


(4, 3)

In [45]:
lhs = PlanLHS(A,ndim=2,axis=1,method="numpy")


In [16]:
lhs.A
lhs.solve(b)

b.shape

(4, 3)

In [17]:
rhs = PlanRHS(A,ndim=2,axis=1)
rhs.A.value

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [18]:
rhs.solve(b)

array([[ 5, 15, 18],
       [19, 48, 54],
       [33, 78, 81],
       [ 9, 24, 27]])

In [19]:
A@b.T

array([[ 5, 19, 33,  9],
       [15, 48, 78, 24],
       [18, 54, 81, 27]])

## Solverplan

In [56]:
%load_ext autoreload
%autoreload 2
import numpy as np 
import matplotlib.pyplot as plt
import scipy.sparse as sp
from pypde.solver.matrix import *
from pypde.solver.plans import *
from pypde.solver.solverplan import *

A = np.array([[1,1,2],[0,3,6],[0,0,9]])
b = np.array([[0,1,2],[3,4,6]])
#x = np.array([1,2,3])
#b = np.vstack((b,x))
print(b.shape)

solver = SolverPlan()

rhs = PlanRHS(A,ndim=2,axis=1)
lhs = PlanLHS(A,ndim=2,axis=1,method="numpy")

solver.add_lhs(lhs)
solver.add_rhs(rhs)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
(2, 3)


In [57]:
solver.show_plan()

Plans RHS:
1 ) Apply method 'multiply' along axis 1 

Plans LHS:
1 ) Apply method 'numpy' along axis 1 



In [54]:
rhs = solver.solve_rhs(b)
solver.solve_lhs(rhs)

array([[0., 1., 2.],
       [3., 4., 6.]])

In [48]:
rhs = b@A.T
np.linalg.solve(A,rhs.T).T

array([[0., 1., 2.],
       [3., 4., 6.]])