In [1]:
import sys
sys.path.append("../")

import numpy as np 
from pypde.bases.linalg.tdma import TDMA

## Diagonals -1, 0, +1

In [2]:
%load_ext autoreload
%autoreload 2

N = 10
a = np.arange(N-1) +1
b = np.arange(N) + 2
c = np.arange(N-1) + 3

d = range(N)

A = np.diag(a,-1) + np.diag(b,0) + np.diag(c,1)

## Diagonals -2, 0, +2

In [8]:
import numpy as np
from pypde.bases.linalg.tdma import TDMA_offset as TDMA
N = 10
a = np.arange(N-2) +1
b = np.arange(N) + 3
c = np.arange(N-2) + 6

d = np.array( np.arange(N) )
d = np.array([d,d]).T

A = np.diag(a,-2) + np.diag(b,0) + np.diag(c,2)

(10, 2)


In [9]:
xnp = np.linalg.solve(A,d)
xnp

array([[-4.44837758, -4.44837758],
       [-4.16961091, -4.16961091],
       [ 2.22418879,  2.22418879],
       [ 2.52549195,  2.52549195],
       [-0.5840708 , -0.5840708 ],
       [-0.42374776, -0.42374776],
       [ 0.14159292,  0.14159292],
       [-0.15563506, -0.15563506],
       [ 0.63716814,  0.63716814],
       [ 0.85375671,  0.85375671]])

In [7]:
x = TDMA(a,b,c,d,2)
x

array([-4.44837758, -4.16961091,  2.22418879,  2.52549195, -0.5840708 ,
       -0.42374776,  0.14159292, -0.15563506,  0.63716814,  0.85375671])

## Fortran

In [3]:
import sys
sys.path.append("../")
import numpy as np 
from pypde.bases.linalg.fortran import tdma
from pypde.bases.linalg.tdma import TDMA_Fortran as TDMA

N = 10
a = np.arange(N-2) +1
b = np.arange(N) + 3
c = np.arange(N-2) + 6

d = np.array( np.arange(N) )
d2 = np.array([d,d]).T

x = TDMA(a,b,c,d,2)
x

array([-4.44837758, -4.16961091,  2.22418879,  2.52549195, -0.5840708 ,
       -0.42374776,  0.14159292, -0.15563506,  0.63716814,  0.85375671])

In [5]:
x = TDMA(a,b,c,d2,2)
x

array([[-4.44837758, -4.44837758],
       [-4.16961091, -4.16961091],
       [ 2.22418879,  2.22418879],
       [ 2.52549195,  2.52549195],
       [-0.5840708 , -0.5840708 ],
       [-0.42374776, -0.42374776],
       [ 0.14159292,  0.14159292],
       [-0.15563506, -0.15563506],
       [ 0.63716814,  0.63716814],
       [ 0.85375671,  0.85375671]])

In [16]:
print(tdma.__doc__)


This module 'tdma' is auto-generated with f2py (version:2).
Functions:
  solve_tdma_1d(l,d,u,k,x,n=len(x))
.


In [13]:
b

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
c

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [9]:
x

array([-4.44837758, -4.16961091,  2.22418879,  2.52549195, -0.5840708 ,
       -0.42374776,  0.14159292, -0.15563506,  0.63716814,  0.85375671])